#ci.gocd.yaml
environments:
  itzero-uat:
    pipelines:
      - itzero-uat
pipelines:
  itzero-uat:
    group: itzero # note that the group name can contain only of alphanumeric & underscore characters
    materials:
      src:
        git: https://github.com/Hippoom/itzero-ops.git
      build-upstream:
        pipeline: itzero-build
        stage: build
    stages:
      - deploy:
          approval:
            type: manual
          jobs:
            deploy:
              resources:
               - jdk8
              artifacts:
               - build:
                   source: build/version
                   destination: build
               - test:
                   source: build/reports
                   destination: build
              tabs:
                build_info: build/version
                test: build/reports/tests/smoke/index.html
              tasks:
               - script: rm -rf build # cleanup
               - fetch:
                   pipeline: itzero-build
                   stage: build
                   job: build
                   is_file: yes
                   source: build/version
                   destination: build
               - script: ./scripts/fetch-artifacts.sh
               - script: ./scripts/deploy-uat.sh
               - script: ./scripts/smoke.sh uat $(cat build/version) http://192.168.47.11 8080